### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by SumitKanth** [Bauddhik-Geeks/Resource-Card#19]
This website don't have a logo, I will add a logo to it.

Can you assign me ?

**Comment by Rajkumar-justcoder** [comment]
Here you go

**Comment by Shravanikale** [comment]
Hey @Rajkumar-justcoder I want to work on this issue can you please assign this to me!!😇

**Comment by SumitKanth** [comment]
@Rajkumar-justcoder what type of logo I should add ? can you give me idea ?

**Comment by Rajkumar-justcoder** [comment]
@Nitesh-thapliyal  can u pls help

**Comment by Rajkumar-justcoder** [comment]
> Hey @Rajkumar-justcoder I want to work on this issue can you please assign this to me!!innocent

sry its already assign to sumit

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal can you help plz

**Comment by Nitesh-thapliyal** [comment]
> sry its already assign to sumit

yes, how can I help you??

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal What type of logo should I add ?

**Comment by Nitesh-thapliyal** [comment]
> 

ummm, something related to learning or searching

**Comment by SumitKanth** [comment]
@Nitesh-thapliyal okii
