### ISSUE TITLE
Change the text color from black to white in the search bar in the dark mode

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Resource-Card#29]
- change the text color from black to white in the search bar
![Screenshot from 2022-10-03 20-18-54](https://user-images.githubusercontent.com/53345517/193609126-78689e77-9d87-487b-8efd-b49084d32043.png)

**Comment by aniket2003** [comment]
@Nitesh-thapliyal I would like to work on this. Can you please assign me.

**Comment by Nitesh-thapliyal** [comment]
Great! @aniket2003 assigning this to you!!

**Comment by anirudh0806** [comment]
Could you assign this work to me?

**Comment by Rajkumar-justcoder** [comment]
Its already assign to aniket , you can see other issue
