### ISSUE TITLE
Dev Resources

### ISSUE THREAD

**Issue by SumitKanth** [Bauddhik-Geeks/Resource-Card#7]
I will add useful dev resources in the given format.

Can you plz assign me ?

**Comment by Rajkumar-justcoder** [comment]
Yeah sure good to go!!

**Comment by Rajkumar-justcoder** [comment]
hey I guess its is done now.

**Comment by Rajkumar-justcoder** [comment]
> hey I guess its is done now.

if yes then pls close pr else let me know

**Comment by SumitKanth** [comment]
@Rajkumar-justcoder  Yes its done
